# Generated by Django 5.1 on 2024-08-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registration_no',
            new_name='registrationNo',
        ),
    ]
